Fix merge-gatekeeper on push event (#10)

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -216,7 +216,7 @@ jobs:
                         --define sonar.analysis.cache.enabled=false
 
     merge-gatekeeper:
-        if: always()
+        if: ${{ always() && github.event_name == 'pull_request' }}
         runs-on: ubuntu-latest
         needs:
             - Build
@@ -230,10 +230,6 @@ jobs:
             checks: read
             statuses: read
         steps:
-            -   name: Exit early if not a PR and avoid running merge-gatekeeper
-                if: github.event_name != 'pull_request'
-                run: exit 0
-
             -   name: Run Merge Gatekeeper
                   # NOTE: v1 is updated to reflect the latest v1.x.y. Please use any tag/branch that suits your needs:
                 #       https://github.com/upsidr/merge-gatekeeper/tags
@@ -247,6 +243,12 @@ jobs:
         runs-on: ubuntu-latest
         needs:
             - merge-gatekeeper
-        if: ${{ always() && (needs.merge-gatekeeper.result == 'success' || needs.merge-gatekeeper.result == 'skipped') }}
+        if: always()
         steps:
-            - run: echo "All jobs completed successfully!"
+            -   name: Check merge-gatekeeper result
+                run: |
+                    if [ "${{ needs.merge-gatekeeper.result }}" = "failure" ]; then
+                      echo "Merge Gatekeeper failed."
+                      exit 1
+                    fi
+                    echo "CI passed."
